#############################################################################
# Makefile for building: Demo_meeting
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Mar 30 23:41:48 2015
# Project:  Demo_meeting.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Demo_meeting.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread -lcurl
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Advanced_Search.cpp \
		getPrice.cpp \
		main.cpp \
		MainWindow.cpp \
		Money.cpp \
		MoveDialog.cpp \
		Order.cpp \
		Portfolio.cpp \
		SelectStartingDate.cpp \
		Stock.cpp moc_Advanced_Search.cpp \
		moc_MainWindow.cpp \
		moc_MoveDialog.cpp \
		moc_SelectStartingDate.cpp
OBJECTS       = Advanced_Search.o \
		getPrice.o \
		main.o \
		MainWindow.o \
		Money.o \
		MoveDialog.o \
		Order.o \
		Portfolio.o \
		SelectStartingDate.o \
		Stock.o \
		moc_Advanced_Search.o \
		moc_MainWindow.o \
		moc_MoveDialog.o \
		moc_SelectStartingDate.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Demo_meeting.pro
QMAKE_TARGET  = Demo_meeting
DESTDIR       = 
TARGET        = Demo_meeting

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Advanced_Search.h ui_MainWindow.h ui_MoveDialog.h ui_SelectStartingDate.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Demo_meeting.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Demo_meeting.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Demo_meeting.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Demo_meeting1.0.0 || $(MKDIR) .tmp/Demo_meeting1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Demo_meeting1.0.0/ && $(COPY_FILE) --parents Advanced_Search.h getPrice.h headers.h MainWindow.h Money.h MoveDialog.h Order.h Portfolio.h SelectStartingDate.h Stock.h .tmp/Demo_meeting1.0.0/ && $(COPY_FILE) --parents Advanced_Search.cpp getPrice.cpp main.cpp MainWindow.cpp Money.cpp MoveDialog.cpp Order.cpp Portfolio.cpp SelectStartingDate.cpp Stock.cpp .tmp/Demo_meeting1.0.0/ && $(COPY_FILE) --parents Advanced_Search.ui MainWindow.ui MoveDialog.ui SelectStartingDate.ui .tmp/Demo_meeting1.0.0/ && (cd `dirname .tmp/Demo_meeting1.0.0` && $(TAR) Demo_meeting1.0.0.tar Demo_meeting1.0.0 && $(COMPRESS) Demo_meeting1.0.0.tar) && $(MOVE) `dirname .tmp/Demo_meeting1.0.0`/Demo_meeting1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Demo_meeting1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Advanced_Search.cpp moc_MainWindow.cpp moc_MoveDialog.cpp moc_SelectStartingDate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Advanced_Search.cpp moc_MainWindow.cpp moc_MoveDialog.cpp moc_SelectStartingDate.cpp
moc_Advanced_Search.cpp: ui_Advanced_Search.h \
		Advanced_Search.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) Advanced_Search.h -o moc_Advanced_Search.cpp

moc_MainWindow.cpp: ui_MainWindow.h \
		headers.h \
		Stock.h \
		Money.h \
		Portfolio.h \
		getPrice.h \
		Order.h \
		MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_MoveDialog.cpp: ui_MoveDialog.h \
		MoveDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MoveDialog.h -o moc_MoveDialog.cpp

moc_SelectStartingDate.cpp: ui_SelectStartingDate.h \
		SelectStartingDate.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) SelectStartingDate.h -o moc_SelectStartingDate.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Advanced_Search.h ui_MainWindow.h ui_MoveDialog.h ui_SelectStartingDate.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Advanced_Search.h ui_MainWindow.h ui_MoveDialog.h ui_SelectStartingDate.h
ui_Advanced_Search.h: Advanced_Search.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic Advanced_Search.ui -o ui_Advanced_Search.h

ui_MainWindow.h: MainWindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic MainWindow.ui -o ui_MainWindow.h

ui_MoveDialog.h: MoveDialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic MoveDialog.ui -o ui_MoveDialog.h

ui_SelectStartingDate.h: SelectStartingDate.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic SelectStartingDate.ui -o ui_SelectStartingDate.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Advanced_Search.o: Advanced_Search.cpp Advanced_Search.h \
		ui_Advanced_Search.h \
		headers.h \
		Stock.h \
		Money.h \
		Portfolio.h \
		getPrice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Advanced_Search.o Advanced_Search.cpp

getPrice.o: getPrice.cpp headers.h \
		Stock.h \
		Money.h \
		Portfolio.h \
		getPrice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getPrice.o getPrice.cpp

main.o: main.cpp MainWindow.h \
		ui_MainWindow.h \
		headers.h \
		Stock.h \
		Money.h \
		Portfolio.h \
		getPrice.h \
		Order.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_MainWindow.h \
		headers.h \
		Stock.h \
		Money.h \
		Portfolio.h \
		getPrice.h \
		Order.h \
		SelectStartingDate.h \
		ui_SelectStartingDate.h \
		Advanced_Search.h \
		ui_Advanced_Search.h \
		MoveDialog.h \
		ui_MoveDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

Money.o: Money.cpp Money.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Money.o Money.cpp

MoveDialog.o: MoveDialog.cpp MoveDialog.h \
		ui_MoveDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoveDialog.o MoveDialog.cpp

Order.o: Order.cpp headers.h \
		Stock.h \
		Money.h \
		Portfolio.h \
		getPrice.h \
		Order.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Order.o Order.cpp

Portfolio.o: Portfolio.cpp headers.h \
		Stock.h \
		Money.h \
		Portfolio.h \
		getPrice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Portfolio.o Portfolio.cpp

SelectStartingDate.o: SelectStartingDate.cpp SelectStartingDate.h \
		ui_SelectStartingDate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SelectStartingDate.o SelectStartingDate.cpp

Stock.o: Stock.cpp Stock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stock.o Stock.cpp

moc_Advanced_Search.o: moc_Advanced_Search.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Advanced_Search.o moc_Advanced_Search.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MoveDialog.o: moc_MoveDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MoveDialog.o moc_MoveDialog.cpp

moc_SelectStartingDate.o: moc_SelectStartingDate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SelectStartingDate.o moc_SelectStartingDate.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

